spring:
  docker:
    compose:
      enabled: false

  cache:
    type: caffeine
    cache-names:
      - activeEvents
    caffeine:
      spec: "maximumSize=100,expireAfterWrite=1h"

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:maple_info_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

nexon:
  api:
    url: https://open.api.nexon.com
    key: test_e1cea6e7b4e7c3790fdb7f901aa4459945925c3884c1026b7b5349b283717b29efe8d04e6d233bd35cf2fabdeb93fb0d

gemini:
  api-key: ${GEMINI_API_KEY}

jwt:
  secret: ${JWT_SECRET}