spring:


  docker:
    compose:
      enabled: false

  cache:
    type: caffeine
    cache-names:
      - activeEvents
    caffeine:
      spec: "maximumSize=100,expireAfterWrite=1h"

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:maple_info_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

nexon:
  api:
    url: https://open.api.nexon.com
    key: ${NEXON_API_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}

jwt:
  secret: ${JWT_SECRET}

# application-local.yaml
app:
  frontend-url: http://localhost:5173